INFO:root:Executed R('load(\'../../instructor/assignments/hw1/ex1-tests.rda\')')
INFO:root:(1 points) R('all.equal(ex1.data, sol$ex1.data)')[0] is True
INFO:root:(1 points) R('all.equal(ex1.data.v, sol$ex1.data.v)')[0] is True
ERROR:root:(1 points) Checking R('all.equal(n.ex1.data, sol$n.ex1.data)')[0]
ERROR:root:... Expecting: True
ERROR:root:... But got:   Traceback error
ERROR:root:Got exception:
Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.ex1.data, sol$n.ex1.data) : 
  object 'n.ex1.data' not found

ERROR:root:Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.ex1.data, sol$n.ex1.data) : 
  object 'n.ex1.data' not found

Traceback (most recent call last):
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/gradebook/score.py", line 180, in check
    result = eval(command, g)
  File "<string>", line 1, in <module>
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/__init__.py", line 246, in __call__
    res = self.eval(p)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 166, in __call__
    return super(SignatureTranslatedFunction, self).__call__(*args, **kwargs)
  File "/Users/Karl/anaconda/lib/python2.7/site-packages/rpy2/robjects/functions.py", line 99, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
RRuntimeError: Error in all.equal(n.ex1.data, sol$n.ex1.data) : 
  object 'n.ex1.data' not found

INFO:root:(1 points) R('all.equal(data.mean, sol$data.mean)')[0] is True
INFO:root:(1 points) R('all.equal(data.mean.trimmed, sol$data.mean.trimmed)')[0] is True
INFO:root:(1 points) R('all.equal(data.sd, sol$data.sd)')[0] is True
INFO:root:(1 points) R('all.equal(min.ex1.data, sol$min.ex1.data)')[0] is True
INFO:root:(1 points) R('all.equal(max.ex1.data, sol$max.ex1.data)')[0] is True
INFO:root:(1 points) R('all.equal(data.summary, sol$data.summary)')[0] is True
INFO:root:(1 points) R('all.equal(ex1.data.double, sol$ex1.data.double)')[0] is True
INFO:root:(1 points) R('all.equal(ex1.data.sum, sol$ex1.data.sum)')[0] is True
INFO:root:(1 points) R('all.equal(random.data, sol$random.data)')[0] is True
INFO:root:(1 points) R('all.equal(100, length(random.data))')[0] is True
INFO:root:(1 points) R('all.equal(data.cor, sol$data.cor)')[0] is True
INFO:root:You got a 13 out of 14.
